**Importing libraries**

In [135]:
import numpy as np  # scientific computing tools

**Defining Sigmoid activation function structures**

In [136]:
# returns sigmoid function value or sigmoid derivative of a x value, dependind
# on @isDerivative parameter passed
def sigmoid(x, isDerivative=False):
    if isDerivative:
        return sigmoid(x) * (1 - sigmoid(x))
    return 1 / (1 + np.exp(-x))

**Defining TANH activation function structures**

In [137]:
# returns TANH function value or TANH derivative of a x value, dependind
# on @isDerivative parameter passed
def tanh(x, isDerivative=False):
    if isDerivative:
        return 1 - np.tanh(x) ** 2
    return np.tanh(x)

**Defining Backpropagation structure**

In [138]:
class NeuralNetwork:
    def __init__(self, input_size, hidden_size, output_size, learning_rate, activation_func):
        self.input_size = input_size
        self.hidden_size = hidden_size
        self.output_size = output_size
        self.learning_rate = learning_rate
        self.activation_func = activation_func
        # generates random weights values
        self.weights1 = np.random.uniform(size=(self.input_size, self.hidden_size))
        self.weights2 = np.random.uniform(size=(self.hidden_size, self.output_size))
    
    def feedforward(self, X):
        # process hidden layer output with arguments weights and inputs
        self.hidden_layer = self.activation_func(np.dot(X, self.weights1))

        # process output layer based on hidden layer
        self.output_layer = self.activation_func(np.dot(self.hidden_layer, self.weights2))
        return self.output_layer
    
    # update weights based on error metrics to obtain more precise results
    def backpropagation(self, X, y, output):
        error = y - output

        # process the derivative of the activation function applied 
        # to the dot product of the hidden layer
        d_output = error * self.activation_func(np.dot(self.hidden_layer, self.weights2), isDerivative=True)

        # process the error for the hidden layer by taking the dot product
        error_hidden = d_output.dot(self.weights2.T)

        # process the derivative of the activation function applied to the dot 
        # product of the input layer and the first set of weights
        d_hidden = error_hidden * self.activation_func(np.dot(X, self.weights1), isDerivative=True)
        self.weights1 += self.learning_rate * X.T.dot(d_hidden)
        self.weights2 += self.learning_rate * self.hidden_layer.T.dot(d_output)
    
    def train(self, X, y):
        output = self.feedforward(X)
        self.backpropagation(X, y, output)

**Creating input samples to test AND operation**

In [139]:
X = np.array([[0,0],[0,1],[1,0],[1,1]])
y_and = np.array([[0],[0],[0],[1]])

*Testing AND prediction with Sigmoid*

In [140]:
and_sigmoid = NeuralNetwork(2, 2, 1, 1, sigmoid)

for i in range(10000):
    and_sigmoid.train(X, y_and)

*Testing AND prediction with TANH*

In [141]:
and_tanh = NeuralNetwork(2, 2, 1, 1, tanh)

for i in range(10000):
    and_tanh.train(X, y_and)

*Sigmoid AND results*

In [142]:
print(and_sigmoid.feedforward(X))

[[0.00139573]
 [0.00991014]
 [0.01044492]
 [0.49948785]]


*TANH AND results*

In [143]:
print(and_tanh.feedforward(X))

[[ 0.        ]
 [ 0.55304927]
 [-0.20384775]
 [ 0.85409958]]


**Creating input samples to test OR operation**

In [144]:
X = np.array([[0,0],[0,1],[1,0],[1,1]])
y_or = np.array([[0],[1],[1],[1]])

*Testing OR prediction with Sigmoid*

In [145]:
or_sigmoid = NeuralNetwork(2, 2, 1, 1, sigmoid)

for i in range(10000):
    or_sigmoid.train(X, y_and)

*Testing OR prediction with TANH*

In [146]:
or_tanh = NeuralNetwork(2, 2, 1, 1, tanh)

for i in range(10000):
    or_tanh.train(X, y_and)

*Sigmoid OR results*

In [147]:
print(or_sigmoid.feedforward(X))

[[0.00105014]
 [0.01036121]
 [0.00951478]
 [0.4994781 ]]


*TANH OR results*

In [148]:
print(or_tanh.feedforward(X))

[[ 0.        ]
 [ 0.55316385]
 [-0.20392081]
 [ 0.85430558]]


**Creating input samples to test XOR operations**

In [149]:
X = np.array([[0,0],[0,1],[1,0],[1,1]])
y_or = np.array([[0],[1],[1],[0]])

*Testing XOR prediction with Sigmoid*

In [150]:
xor_sigmoid = NeuralNetwork(2, 2, 1, 1, sigmoid)

for i in range(10000):
    xor_sigmoid.train(X, y_and)

*Testing XOR prediction with TANH*

In [151]:
xor_tanh = NeuralNetwork(2, 2, 1, 1, tanh)

for i in range(10000):
    xor_tanh.train(X, y_and)

*Sigmoid XOR results*

In [152]:
print(xor_sigmoid.feedforward(X))

[[0.00218994]
 [0.02237539]
 [0.02900784]
 [0.97420458]]


*TANH XOR results*

In [153]:
print(xor_tanh.feedforward(X))

[[ 0.        ]
 [-0.20392375]
 [ 0.55316813]
 [ 0.85431324]]
